model: /home/yeojin/yolo_train/train/yolo11n.pt
data: ./dataset.yaml
device: cuda
imgsz: 480
epochs: 150
batch: 512
patience: 70
workers: 8
optimizer: AdamW
project: ./runs/train
name: model_name
plots: true
hsv_h: 0.1
hsv_s: 0.0
hsv_v: 0.0
degrees: 0.0
translate: 0.2
scale: 0.7
shear: 0.2
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 0.5
mixup: 0.1
copy_paste: 0.0
dropout: 0.2
